### PR TITLE
Support undefined arrays

### PR DESCRIPTION
**Pull request by adriancarriger**

### CODE REVIEW

**Comment by taylorreece** [comment]
Is the goal of this to make it so things like `myArray.forEach` will trigger a warning in the editor that `myArray` might be `undefined`?

**Review by kaleb-tringale — APPROVED** [review]
LGTM 👍

**Review by kaleb-tringale — COMMENTED** [review]
Might want to bump the version in the package json correct?

**Comment by adriancarriger** [comment]
@taylorreece that's correct.
@kaleb-tringale good catch! 🎉  Updated here: https://github.com/prismatic-io/spectral/compare/624f6652086e4fb3f3fa874d66ede2eeee226bd1..ded7ba874020a233ed4537074fc1043c3585c93b

**Review by taylorreece — APPROVED** [review]

**Pull request merged**
